# https://probot.github.io/apps/settings/

repository:
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true

labels:
  - name: bug
    description: Confirmed issues that need to be resolved
    color: e99695
  - name: question
    description: Questions, documentations, information, etc
    color: bfd4f2
  - name: feature
    description: Scheduled project enhancements
    color: c2e0c6
  - name: help wanted
    description: Could you please help me with any of these?
    color: fbca04
  - name: on hold
    description: I know this is here, but I'm not working on it
    color: cccccc
  - name: stale
    description: Used exclusively by the stale and lock bots
    color: 000000

branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts: ['build', 'codecov/patch', 'codecov/project']
      enforce_admins: true
      restrictions: null
